use std::collections::{HashMap, VecDeque};
use std::path::PathBuf;
use std::time::{Duration, Instant};
use reqwest::Client;
use serde_json::json;
use tracing::{info, warn};

use crate::config::{AiAdvisorConfig, AiProvider};
use crate::event::{Action, EventType, NormalizedEvent};

/// Identifies a repeated security pattern (binary + target + action).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct PatternKey {
    binary: String,
    detail: String,
    action: String,
}

pub struct AiAdvisor {
    cfg:            AiAdvisorConfig,
    rules_path:     String,
    window:         VecDeque<(Instant, NormalizedEvent)>,
    counts:         HashMap<PatternKey, u32>,
    cooldowns:      HashMap<PatternKey, Instant>,
    http:           Client,
}

impl AiAdvisor {
    pub fn new(cfg: AiAdvisorConfig, rules_path: String) -> Self {
        Self {
            cfg,
            rules_path,
            window:    VecDeque::new(),
            counts:    HashMap::new(),
            cooldowns: HashMap::new(),
            http:      Client::new(),
        }
    }

    pub fn update_config(&mut self, cfg: AiAdvisorConfig) {
        self.cfg = cfg;
    }

    pub async fn analyze(&mut self, event: &NormalizedEvent) {
        if !self.cfg.enabled {
            return;
        }

        // Only track blocked or alerted events
        if !matches!(event.action, Action::Blocked | Action::Alerted | Action::Killed) {
            return;
        }

        let key = match Self::pattern_key(event) {
            Some(k) => k,
            None => return,
        };

        let now = Instant::now();
        let window_dur = Duration::from_secs(self.cfg.window_secs);

        // Evict expired events
        while let Some((ts, _)) = self.window.front() {
            if now.duration_since(*ts) > window_dur {
                let (_, old) = self.window.pop_front().unwrap();
                if let Some(old_key) = Self::pattern_key(&old) {
                    if let Some(c) = self.counts.get_mut(&old_key) {
                        *c = c.saturating_sub(1);
                        if *c == 0 { self.counts.remove(&old_key); }
                    }
                }
            } else {
                break;
            }
        }

        self.window.push_back((now, event.clone()));
        let count = {
            let c = self.counts.entry(key.clone()).or_insert(0);
            *c += 1;
            *c
        };

        if count < self.cfg.trigger_threshold {
            return;
        }

        // Check cooldown
        if let Some(&last) = self.cooldowns.get(&key) {
            if now.duration_since(last) < Duration::from_secs(self.cfg.cooldown_seconds) {
                return;
            }
        }
        self.cooldowns.insert(key.clone(), now);

        let api_key = match self.resolve_api_key() {
            Some(k) => k,
            None => {
                warn!(
                    "AI advisor: env var '{}' empty or unset — skipping",
                    self.cfg.api_key_env
                );
                return;
            }
        };

        info!("AI advisor triggered: pattern={:?} count={}", key, count);

        // Collect context events (most recent first)
        let context: Vec<NormalizedEvent> = self.window.iter()
            .rev()
            .take(self.cfg.context_window_size)
            .map(|(_, ev)| ev.clone())
            .collect();

        let prompt = self.build_prompt(&context);

        let toml_block = match self.cfg.provider {
            AiProvider::Anthropic => self.call_anthropic(&prompt, &api_key).await,
            AiProvider::Openai    => self.call_openai(&prompt, &api_key).await,
        };

        let Some(toml_block) = toml_block else { return; };

        if let Err(e) = toml::from_str::<toml::Value>(&toml_block) {
            warn!("AI advisor: invalid TOML from provider: {}", e);
            return;
        }

        let out_path = PathBuf::from(&self.rules_path).join("ai-generated.toml");
        let header = "# Auto-generated by VectorGuard AI Advisor — do not edit manually\n\n";
        match std::fs::write(&out_path, format!("{}{}", header, toml_block)) {
            Ok(_)  => info!("AI advisor: rules written to {}", out_path.display()),
            Err(e) => warn!("AI advisor: failed to write rules: {}", e),
        }
    }

    fn resolve_api_key(&self) -> Option<String> {
        if self.cfg.api_key_env.is_empty() {
            return None;
        }
        std::env::var(&self.cfg.api_key_env).ok().filter(|k| !k.is_empty())
    }

    fn pattern_key(event: &NormalizedEvent) -> Option<PatternKey> {
        let detail = match &event.event_type {
            EventType::FileAccess { path, .. } => path.clone(),
            EventType::Network { port, .. }    => port.to_string(),
            EventType::Exec                    => event.process.binary.clone(),
            _ => return None,
        };
        Some(PatternKey {
            binary: event.process.binary.clone(),
            detail,
            action: format!("{:?}", event.action),
        })
    }

    fn build_prompt(&self, context: &[NormalizedEvent]) -> String {
        let events_summary: Vec<String> = context.iter().map(|ev| {
            let type_str = match &ev.event_type {
                EventType::FileAccess { path, .. }           => format!("file_access path={}", path),
                EventType::Network { port, remote_ip, .. }   => format!("network remote={}:{}", remote_ip, port),
                EventType::Exec                              => "exec".to_string(),
                EventType::Privilege { syscall, .. }         => format!("privilege syscall={}", syscall),
                EventType::Signal { signum, .. }             => format!("signal sig={}", signum),
            };
            format!(
                "binary={} uid={} action={:?} type={} rule={:?}",
                ev.process.binary,
                ev.process.uid,
                ev.action,
                type_str,
                ev.rule_name,
            )
        }).collect();

        let current_rules = self.load_current_rules();

        format!(
            "You are a security rule advisor for VectorGuard, an eBPF-based security monitoring tool.\n\
             \n\
             Current fast-path rules (TOML):\n\
             ```toml\n{current_rules}```\n\
             \n\
             Recent anomalous events (repeated pattern detected):\n\
             {events}\n\
             \n\
             Based on this pattern, suggest 1-3 new security rules. \
             Use this TOML structure (all match fields are optional, AND-combined):\n\
             ```toml\n\
             [[rules]]\n\
             name              = \"rule-name\"      # unique, kebab-case\n\
             action            = \"alert\"           # block | alert | log\n\
             match_process     = [\"binary\"]        # process comm name globs\n\
             match_path_prefix = [\"/path/\"]       # file path prefixes\n\
             match_exec_path   = [\"/bin/sh\"]      # executed binary path prefixes\n\
             match_port        = [4444]             # destination ports\n\
             match_uid         = 0                  # user ID\n\
             ```\n\
             Reply with only the TOML block(s), no commentary.",
            current_rules = current_rules,
            events = events_summary.join("\n"),
        )
    }

    async fn call_anthropic(&self, prompt: &str, api_key: &str) -> Option<String> {
        let model = if self.cfg.model.is_empty() { "claude-sonnet-4-6" } else { &self.cfg.model };
        let body = json!({
            "model": model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}]
        });

        let resp = self.http
            .post("https://api.anthropic.com/v1/messages")
            .header("x-api-key", api_key)
            .header("anthropic-version", "2023-06-01")
            .header("content-type", "application/json")
            .json(&body)
            .send()
            .await
            .map_err(|e| warn!("AI advisor HTTP error (anthropic): {}", e))
            .ok()?;

        let json_resp: serde_json::Value = resp.json().await
            .map_err(|e| warn!("AI advisor response parse error (anthropic): {}", e))
            .ok()?;

        let text = json_resp["content"][0]["text"].as_str().unwrap_or("");
        let toml_block = Self::extract_toml(text);
        if toml_block.is_empty() {
            warn!("AI advisor (anthropic): no TOML found in response");
            return None;
        }
        Some(toml_block)
    }

    async fn call_openai(&self, prompt: &str, api_key: &str) -> Option<String> {
        let model = if self.cfg.model.is_empty() { "gpt-4o" } else { &self.cfg.model };
        let body = json!({
            "model": model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}]
        });

        let resp = self.http
            .post("https://api.openai.com/v1/chat/completions")
            .header("Authorization", format!("Bearer {}", api_key))
            .header("content-type", "application/json")
            .json(&body)
            .send()
            .await
            .map_err(|e| warn!("AI advisor HTTP error (openai): {}", e))
            .ok()?;

        let json_resp: serde_json::Value = resp.json().await
            .map_err(|e| warn!("AI advisor response parse error (openai): {}", e))
            .ok()?;

        let text = json_resp["choices"][0]["message"]["content"].as_str().unwrap_or("");
        let toml_block = Self::extract_toml(text);
        if toml_block.is_empty() {
            warn!("AI advisor (openai): no TOML found in response");
            return None;
        }
        Some(toml_block)
    }

    fn load_current_rules(&self) -> String {
        let mut out = String::new();
        if let Ok(entries) = std::fs::read_dir(&self.rules_path) {
            let mut paths: Vec<_> = entries.flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().map(|e| e == "toml").unwrap_or(false))
                .collect();
            paths.sort();
            for p in paths {
                if let Ok(content) = std::fs::read_to_string(&p) {
                    out.push_str(&content);
                    out.push('\n');
                }
            }
        }
        out
    }

    /// Extract TOML from a fenced code block (```toml ... ```) or raw content.
    fn extract_toml(text: &str) -> String {
        let mut result = String::new();
        let mut in_block = false;

        for line in text.lines() {
            if !in_block {
                if line.starts_with("```toml") || line.trim_start().starts_with("```toml") {
                    in_block = true;
                }
            } else if line.trim() == "```" {
                in_block = false;
            } else {
                result.push_str(line);
                result.push('\n');
            }
        }

        // Fallback: raw TOML with no fence
        if result.is_empty() && text.contains("[[rules]]") {
            return text.to_string();
        }

        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::*;

    fn evt(event_type: EventType, action: Action, binary: &str) -> NormalizedEvent {
        NormalizedEvent {
            id: 0,
            timestamp: 0,
            source: EventSource::NativeEbpf,
            process: ProcessInfo {
                pid: 1, ppid: 0, uid: 0, gid: 0,
                binary: binary.into(),
                args: vec![], cwd: String::new(),
            },
            parent: None,
            event_type,
            severity: Severity::High,
            action,
            rule_name: None,
            k8s: None,
            raw: serde_json::Value::Null,
        }
    }

    // ── extract_toml ─────────────────────────────────────────

    #[test]
    fn extract_toml_handles_fenced_block() {
        let resp = "Here's the rule:\n```toml\n[[rules]]\nname = \"x\"\n```\n";
        let out = AiAdvisor::extract_toml(resp);
        assert!(out.contains("[[rules]]"));
        assert!(out.contains("name = \"x\""));
        assert!(!out.contains("```"));
    }

    #[test]
    fn extract_toml_falls_back_to_raw_rules() {
        let resp = "[[rules]]\nname = \"y\"\naction = \"alert\"\n";
        let out = AiAdvisor::extract_toml(resp);
        assert!(out.contains("[[rules]]"));
        assert!(out.contains("name = \"y\""));
    }

    #[test]
    fn extract_toml_returns_empty_when_no_rule_marker() {
        let resp = "Sorry, I cannot help with that.";
        let out = AiAdvisor::extract_toml(resp);
        assert!(out.is_empty());
    }

    #[test]
    fn extract_toml_concatenates_multiple_fenced_blocks() {
        let resp = "First:\n```toml\n[[rules]]\nname = \"a\"\n```\nSecond:\n```toml\n[[rules]]\nname = \"b\"\n```\n";
        let out = AiAdvisor::extract_toml(resp);
        assert!(out.contains("name = \"a\""));
        assert!(out.contains("name = \"b\""));
    }

    #[test]
    fn extract_toml_block_at_end() {
        let resp = "Analysis: pattern looks like reverse shell.\n```toml\n[[rules]]\nname = \"rs\"\n```";
        let out = AiAdvisor::extract_toml(resp);
        assert!(out.contains("name = \"rs\""));
    }

    // ── pattern_key ──────────────────────────────────────────

    #[test]
    fn pattern_key_file_access_uses_path() {
        let ev = evt(
            EventType::FileAccess {
                path: "/etc/shadow".into(),
                flags: FileFlags { read: true, write: false, execute: false },
            },
            Action::Blocked,
            "cat",
        );
        let k = AiAdvisor::pattern_key(&ev).expect("key");
        assert_eq!(k.binary, "cat");
        assert_eq!(k.detail, "/etc/shadow");
        assert_eq!(k.action, "Blocked");
    }

    #[test]
    fn pattern_key_network_uses_port() {
        let ev = evt(
            EventType::Network {
                direction: Direction::Outbound,
                remote_ip: "1.2.3.4".parse().unwrap(),
                port: 4444,
                proto: Proto::Tcp,
            },
            Action::Alerted,
            "curl",
        );
        let k = AiAdvisor::pattern_key(&ev).expect("key");
        assert_eq!(k.detail, "4444");
    }

    #[test]
    fn pattern_key_exec_uses_binary() {
        let ev = evt(EventType::Exec, Action::Alerted, "bash");
        let k = AiAdvisor::pattern_key(&ev).expect("key");
        assert_eq!(k.detail, "bash");
    }

    #[test]
    fn pattern_key_unsupported_types_return_none() {
        let ev = evt(
            EventType::Signal { signum: 9, target_pid: 42 },
            Action::Alerted,
            "kill",
        );
        assert!(AiAdvisor::pattern_key(&ev).is_none());
    }

    #[test]
    fn pattern_key_distinguishes_actions() {
        let blocked = evt(EventType::Exec, Action::Blocked, "x");
        let alerted = evt(EventType::Exec, Action::Alerted, "x");
        let b = AiAdvisor::pattern_key(&blocked).unwrap();
        let a = AiAdvisor::pattern_key(&alerted).unwrap();
        assert_ne!(b, a);
    }
}
