#![cfg(target_os = "linux")]

use anyhow::{Context, Result};
use aya::{maps::RingBuf, programs::{Lsm, TracePoint}, Ebpf};
use std::{
    net::Ipv4Addr,
    sync::atomic::{AtomicU64, Ordering},
};
use tokio::io::unix::AsyncFd;
use tracing::{debug, info, warn};

use crate::event::{
    Action, Direction, EventSource, EventType, FileFlags, NormalizedEvent,
    ProcessInfo, Proto, Severity,
};
use vectorguard_common::{EventKind, RawEvent};

static EVENT_ID: AtomicU64 = AtomicU64::new(0);

/// Load eBPF program and attach tracepoints + LSM hooks
pub fn load_ebpf() -> Result<Ebpf> {
    // Embed compiled eBPF object into binary (generated by build script)
    static EBPF_DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/vectorguard-ebpf"));

    // Write to temp file and load from disk (avoids potential issues with
    // loading from raw embedded bytes on some kernel/aya combinations)
    let tmp = std::env::temp_dir().join("vectorguard-ebpf.o");
    std::fs::write(&tmp, EBPF_DATA).context("Failed to write eBPF to temp file")?;
    let mut ebpf = aya::EbpfLoader::new()
        .btf(aya::Btf::from_sys_fs().ok().as_ref())
        .load_file(&tmp)
        .context("Failed to load eBPF")?;
    let _ = std::fs::remove_file(&tmp);

    attach_tracepoint(&mut ebpf, "syscalls", "sys_enter_execve", "handle_exec")?;
    attach_tracepoint(&mut ebpf, "syscalls", "sys_enter_openat", "handle_file_open")?;
    attach_tracepoint(&mut ebpf, "syscalls", "sys_enter_connect", "handle_net_connect")?;

    // LSM hooks require CONFIG_BPF_LSM=y (kernel ≥5.7).
    // Gracefully skip if the kernel does not support them.
    attach_lsm(&mut ebpf, "lsm_exec", "bprm_check_security");
    attach_lsm(&mut ebpf, "lsm_file_open", "file_open");

    Ok(ebpf)
}

/// Attach an LSM BPF program. Logs a warning instead of failing if the kernel
/// does not have BPF_LSM support (CONFIG_BPF_LSM=y).
fn attach_lsm(ebpf: &mut Ebpf, prog: &str, hook: &str) {
    let result = (|| -> Result<()> {
        let btf = aya::Btf::from_sys_fs()?;
        let program: &mut Lsm = ebpf
            .program_mut(prog)
            .with_context(|| format!("LSM program {} not found", prog))?
            .try_into()?;
        program.load(hook, &btf)?;
        program.attach()?;
        Ok(())
    })();

    match result {
        Ok(()) => info!("LSM hook '{}' attached ({})", hook, prog),
        Err(e) => warn!(
            "LSM hook '{}' unavailable (kernel may lack CONFIG_BPF_LSM): {}",
            hook, e
        ),
    }
}

fn attach_tracepoint(ebpf: &mut Ebpf, category: &str, name: &str, prog: &str) -> Result<()> {
    let program: &mut TracePoint = ebpf
        .program_mut(prog)
        .with_context(|| format!("Program {} not found", prog))?
        .try_into()?;

    program.load()?;
    program
        .attach(category, name)
        .with_context(|| format!("Failed to attach tracepoint {}/{}", category, name))?;

    Ok(())
}

/// Poll Ring Buffer asynchronously and produce NormalizedEvents
pub async fn run_collector(
    ebpf: &mut Ebpf,
    tx: tokio::sync::mpsc::Sender<NormalizedEvent>,
) -> Result<()> {
    let own_pid = std::process::id();
    let ring_buf = ebpf.map_mut("EVENTS").context("EVENTS map not found")?;
    let ring_buf = RingBuf::try_from(ring_buf)?;
    let mut async_fd = AsyncFd::new(ring_buf)?;

    loop {
        let mut guard = async_fd.readable_mut().await?;
        let rb = guard.get_inner_mut();

        while let Some(item) = rb.next() {
            let raw = parse_raw_event(&item);
            match raw {
                Ok(event) => {
                    // Skip events from our own process to reduce self-noise
                    if event.process.pid == own_pid {
                        continue;
                    }
                    if tx.send(event).await.is_err() {
                        return Ok(()); // receiver closed
                    }
                }
                Err(e) => warn!("Failed to parse event: {}", e),
            }
        }

        guard.clear_ready();
    }
}

fn parse_raw_event(data: &[u8]) -> Result<NormalizedEvent> {
    if data.len() < std::mem::size_of::<RawEvent>() {
        anyhow::bail!("Event data too small: {} bytes", data.len());
    }

    let raw = unsafe { &*(data.as_ptr() as *const RawEvent) };

    let process = ProcessInfo {
        pid:    raw.pid,
        ppid:   raw.ppid,
        uid:    raw.uid,
        gid:    raw.gid,
        binary: raw.comm_str().to_string(),
        args:   vec![],
        cwd:    String::new(),
    };

    let (event_type, severity) = parse_event_type(raw)?;

    // If the eBPF program already took blocking action (SIGKILL / EPERM), reflect that.
    let action = if raw.blocked != 0 { Action::Blocked } else { Action::Allowed };

    Ok(NormalizedEvent {
        id:         EVENT_ID.fetch_add(1, Ordering::Relaxed),
        timestamp:  raw.timestamp,
        source:     EventSource::NativeEbpf,
        process,
        parent:     None,
        event_type,
        severity,
        action,
        rule_name:  None,
        k8s:        None,
        raw:        serde_json::Value::Null,
    })
}

fn parse_event_type(raw: &RawEvent) -> Result<(EventType, Severity)> {
    match raw.kind {
        EventKind::Exec => {
            let filename = unsafe {
                let p = &raw.payload.exec;
                let end = p.filename.iter().position(|&b| b == 0).unwrap_or(256);
                std::str::from_utf8(&p.filename[..end])
                    .unwrap_or("<invalid>")
                    .to_string()
            };
            debug!("exec: {}", filename);
            Ok((EventType::Exec, Severity::Info))
        }

        EventKind::FileOpen => {
            let (path, flags) = unsafe {
                let p = &raw.payload.file;
                let end = p.path.iter().position(|&b| b == 0).unwrap_or(256);
                let path = std::str::from_utf8(&p.path[..end])
                    .unwrap_or("<invalid>")
                    .to_string();
                (path, p.flags)
            };

            let severity = if is_sensitive_path(&path) {
                Severity::High
            } else {
                Severity::Info
            };

            Ok((
                EventType::FileAccess {
                    path,
                    flags: FileFlags {
                        read:    flags & 0x1 == 0, // O_RDONLY=0
                        write:   flags & 0x1 != 0 || flags & 0x2 != 0,
                        execute: false,
                    },
                },
                severity,
            ))
        }

        EventKind::NetConnect => {
            let (dst_ip, dst_port) = unsafe {
                let p = &raw.payload.net;
                let ip = Ipv4Addr::from(u32::from_be(p.dst_ip));
                (ip, p.dst_port)
            };

            Ok((
                EventType::Network {
                    direction: Direction::Outbound,
                    remote_ip: std::net::IpAddr::V4(dst_ip),
                    port:      dst_port,
                    proto:     Proto::Tcp,
                },
                Severity::Info,
            ))
        }

        EventKind::Privilege => Ok((
            EventType::Privilege {
                syscall:    "unknown".to_string(),
                capability: None,
            },
            Severity::High,
        )),
    }
}

/// Determine whether the accessed path is sensitive
fn is_sensitive_path(path: &str) -> bool {
    const SENSITIVE: &[&str] = &[
        "/etc/shadow",
        "/etc/passwd",
        "/etc/sudoers",
        "/root/",
        "/proc/kcore",
        "/proc/kmem",
        "/proc/sysrq-trigger",
        "/proc/sys/kernel/",
        "/sys/kernel/",
    ];
    SENSITIVE.iter().any(|s| path.starts_with(s))
}
